# .github/workflows/docs.yml

name: Deploy Sphinx Docs to GitHub Pages

# Запуск робочого процесу при кожному push до гілки 'main'
# Якщо ваша основна гілка називається 'master', змініть 'main' на 'master'
on:
  push:
    branches:
      - master # Змініть на 'master', якщо ваша основна гілка так називається

# Дозволяємо GitHub Pages читати вміст та розгортати сторінки
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install sphinx sphinx-rtd-theme

    - name: List contents of docs directory # Крок для налагодження
      run: |
        echo "Listing contents of docs directory:"
        ls -la docs/
        echo "Listing contents of docs/_build directory (if exists):"
        ls -la docs/_build/ || true # Додаємо '|| true' щоб крок не провалився, якщо _build ще немає

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Verify build output exists # Крок для налагодження: перевірка наявності папки
      run: |
        echo "Verifying docs/_build/html directory after build:"
        ls -la docs/_build/html/
        test -d docs/_build/html/ # Ця команда провалить крок, якщо директорії немає
      # Якщо цей крок провалиться, це означає, що Sphinx таки не створив папку,
      # або вона була видалена.

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs/_build/html' # Шлях до згенерованих HTML-файлів

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

